# "Beeper feedback" switch
switch:
  - platform: template
    name: ${midea_name} Beeper
    id: midea_beeper
    icon: mdi:volume-source
    restore_state: true
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:
